name: Run the GO app CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch required Go modules
        working-directory: ./docker/05-go-dockerized
        run:  go mod download

      - name: Build
        working-directory: ./docker/05-go-dockerized
        run:  go build -v ./...

      - name: Run functional tests
        working-directory: ./docker/05-go-dockerized
        run:  go test -v ./...
